import React, { StrictMode } from 'react'
import ReactDOM from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'

// The route-tree, autogenerated from the files by Vite on startup!
import { routeTree } from './routeTree.gen.ts'

// A new router instance
const router = createRouter({ routeTree })

// Render the app
ReactDOM.createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>
);